version: '3'

services:
  node-fastify:
    container_name: node-fastify
    build: 
      context: ./
      dockerfile: Dockerfile
    image: andre/node-fastify
    volumes:
      - .:/usr/app
    ports:
      - "3001:3001"
  db:
    image: mongo:6.0.2
    ports:
      - 27017:27017
    volumes:
      - ./.docker/dbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    depends_on:
      - db